version: '3.3'

networks:
    app:

services:
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        expose:
            - ${SERVER_PORT}
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
        environment:
            - SERVER_TYPE=${SERVER_TYPE}
            - SERVER_PORT=${SERVER_PORT}
            - SERVER_HOST=${SERVER_HOST}
            - SERVER_PROTOCOL=${SERVER_PROTOCOL}
        volumes:
            - ./server:/app/server
            - ./storage/logs/error.log:/usr/src/app/server/error.log
        networks:
            - app

    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        environment:
            - REACT_APP_PORT=${CLIENT_PORT}
            - REACT_APP_SERVER_HOST=${SERVER_HOST}
            - REACT_APP_SERVER_PORT=${SERVER_PORT}
            - REACT_APP_SERVER_PROTOCOL=${SERVER_PROTOCOL}
            - CHOKIDAR_USEPOLLING=true
        expose:
            - ${CLIENT_PORT}
        ports:
            - ${CLIENT_PORT}:${CLIENT_PORT}
        volumes:
            - ./client:/app/client
        links:
            - server
        stdin_open: true
        networks:
            - app
